import { pick } from '../core/language.ts';

const zh = {
  copy: '复制',
  copyNothing: '取不到要复制的内容',
  copied: '已复制',
  copyFailed: '复制失败，已展开文本供手动选取',
  imageReadFailed: '读取图片失败',
  canvasUnsupported: '浏览器不支持 canvas,无法缩放图片',
  imageEncodeFailed: '图片重编码失败',
  fileFallback: '文件',
  imageFallback: '图片',
  notImage: (name: string) => `${name} 不是支持的图片格式(JPEG / PNG / WebP / GIF)`,
  undecodable: (name: string) => `${name} 无法解码`,
  stillTooLarge: (name: string, mb: number) => `${name} 缩放后仍超过 ${mb}MB`,
  lamp: {
    online: '正常',
    loading: '启动中',
    error: '故障',
    offline: '未启用',
  },
  cancel: '取消',
  proceedAnyway: '仍要继续',
  confirm: '确认',
  close: '✕ 关闭 (Esc)',
  tooManyImages: (max: number) => `一条消息最多 ${max} 张图`,
  messageInput: '消息输入',
  typeMessage: '输入消息…',
  processingImages: (count: number) => `处理 ${count} 张图片…`,
  enterToSend: 'Enter 发送 · Shift+Enter 换行',
  sendMessage: '发送消息',
  addImage: '添加图片',
  addImageHint: '添加图片（也可粘贴或拖入）',
  removeImage: (name: string) => `移除 ${name}`,
};

const en: typeof zh = {
  copy: 'Copy',
  copyNothing: 'Nothing to copy',
  copied: 'Copied',
  copyFailed: 'Copy failed; text expanded for manual selection',
  imageReadFailed: 'Failed to read image',
  canvasUnsupported: 'This browser does not support canvas; cannot resize image',
  imageEncodeFailed: 'Image re-encoding failed',
  fileFallback: 'File',
  imageFallback: 'Image',
  notImage: (name: string) => `${name} is not a supported image format (JPEG / PNG / WebP / GIF)`,
  undecodable: (name: string) => `${name} could not be decoded`,
  stillTooLarge: (name: string, mb: number) => `${name} still exceeds ${mb}MB after resizing`,
  lamp: {
    online: 'online',
    loading: 'starting',
    error: 'error',
    offline: 'disabled',
  },
  cancel: 'Cancel',
  proceedAnyway: 'Proceed anyway',
  confirm: 'Confirm',
  close: '✕ Close (Esc)',
  tooManyImages: (max: number) => `At most ${max} images per message`,
  messageInput: 'Message input',
  typeMessage: 'Type a message…',
  processingImages: (count: number) => `Processing ${count} image(s)…`,
  enterToSend: 'Enter to send · Shift+Enter for newline',
  sendMessage: 'Send message',
  addImage: 'Add image',
  addImageHint: 'Add image (paste or drop also works)',
  removeImage: (name: string) => `Remove ${name}`,
};

export const S = pick({ zh, en });
