/** 端点表面板与报价编辑器的文案。按 `ctx.language` 选表——面板的语言跟着调用它的那一页走。 */
const zh = {
  saved: '已保存，下一次请求生效。',
  instancesTitle: '供应实例',
  instancesDescription:
    '每个实例独立保存连接、模型档与报价。当前请求与已启动的后台会话保持原有绑定。',
  activeSuffix: ' · 当前',
  instanceField: '供应实例',
  newInstanceName: '新实例名称',
  newInstanceUrl: 'HTTP(S) 供应地址',
  addInstance: '添加实例',
  connectionTitle: '连接',
  connectionDescription: '地址与密钥全局共用：别的部署选中同一实例时读的是同一份。',
  baseUrl: '供应地址',
  secretName: '密钥变量名',
  secretNamePlaceholder: '环境变量名；留空 = 无鉴权',
  secretStatus: '密钥',
  secretSource: { env: '进程环境', file: '端点 .env', none: '未配置' },
  secretValue: '密钥值',
  secretValuePlaceholder: '只写入端点 .env，不回显',
  saveSecret: '写入密钥',
  secretSaved: '密钥已写入端点 .env。',
  secretNameFirst: '先保存密钥变量名，再写入密钥值。',
  multimodal: '接受图片输入',
  endpointPath: '请求路径',
  extraHeaders: '附加请求头（JSON 对象）',
  extraBody: '附加请求体（JSON 对象）',
  jsonObjectRequired: (label: string) => `${label} 必须是 JSON 对象`,
  advancedProtocolTitle: '协议与请求扩展',
  advancedProtocolDescription: '针对 OpenAI Responses 兼容端点的高级配置（端点路径与附加 JSON 字段）。',
  modelFieldLabel: '模型标识',
  effortFieldLabel: '推理强度',
  temperatureFieldLabel: '采样温度',
  specTitle: '模型档',
  specDescription: '配置此实例调用的模型及推理、温度和 Token 限制等生成参数。',
  modelName: '明确模型名',
  fetchModels: '取模型列表',
  modelsFetched: (count: number) => `取到 ${count} 个模型。`,
  modelListFailed: (message: string) => `取不到模型列表：${message}`,
  selectModel: '选择模型',
  unsupportedTier: (current: string) => `当前档位未支持：${current}`,
  thinkingOn: '开启',
  thinkingOff: '关闭',
  effortPlaceholder: '推理强度；空 = 端点默认，none = 关闭',
  effortAria: '推理强度',
  temperaturePlaceholder: '温度默认',
  modelAria: '模型',
  tierAria: '推理档位',
  temperatureAria: '温度',
  maxTokens: '最大输出 token',
  contextWindow: '上下文窗口',
  serviceTier: '服务档',
  serverDefault: '服务端默认',
  activate: '设为当前供应实例',
  probe: '测试可用性',
  probeTitle: '测试结果',
  probeStatus: '状态',
  probeOk: '成功',
  probeFailed: '失败',
  probeLatency: '耗时',
  probeModel: '回显模型',
  probeUsage: '用量',
  probeUsageLine: (input: string, cached: string, output: string, reasoning: string) =>
    `输入 ${input} · 缓存命中 ${cached} · 输出 ${output} · 推理 ${reasoning}`,
  probeEncrypted: '加密思维链',
  yes: '有',
  no: '无',
  probeCost: '本次费用',
  duplicate: '复制',
  duplicateName: '副本名称',
  duplicateConfirm: '复制为',
  duplicated: '已复制。',
  delete: '删除',
  deleteConfirmTitle: (name: string) => `删除实例 ${name}？`,
  deleteConfirmBody: '端点配置与 .env 一并删除。别的部署若选中了它，无法在此得知。',
  deleted: '已删除。',
  pricingTitle: '报价',
  pricingDescription: '历史流水固定使用请求时的报价。自定义报价按模型与费用口径覆盖模块默认值。',
  pricingUnset: '未设报价：这个端点的调用在用量与成本页只计 token，不计金额。',
  meters: {
    input: '输入',
    cachedInput: '缓存命中',
    uncachedInput: '未缓存输入',
    output: '输出',
    reasoning: '推理',
    total: '总量',
  },
  quoteUnknown: (model: string) => `${model}：报价未知`,
  marginal: '边际费用',
  equivalent: 'API 等价费用',
  perMillion: (label: string, rate: number) => `${label} ${rate}/百万`,
  free: '已明确免费',
  bandsNote: '含输入阶梯或服务档；按本次实际用量与服务档计费。',
  rateCached: '缓存命中 / 百万 token',
  rateUncached: '未缓存输入 / 百万 token',
  rateOutput: '输出 / 百万 token',
  currencyField: '币种',
  costFormNote: '基础费率统一适用于全部模型；阶梯或多模型规则请在下方完整规则中配置。',
  costFormOverridden: '当前报价不是三格表能表达的形状，以下方完整规则为准；改动三格表会覆盖它。',
  editFull: '高级定价规则 (JSON)',
  fullNote:
    '空数组恢复模块默认报价；rules 为空数组表示明确免费。完整规则支持输入阶梯、服务档及额外计量单位。',
  viewSnapshot: '查看当前生效报价快照',
};
const en: typeof zh = {
  saved: 'Saved; applies from the next request.',
  instancesTitle: 'Provider instances',
  instancesDescription:
    'Each instance keeps its own connection, model spec and pricing. In-flight requests and running background sessions keep their existing binding.',
  activeSuffix: ' · active',
  instanceField: 'Provider instance',
  newInstanceName: 'New instance name',
  newInstanceUrl: 'HTTP(S) provider URL',
  addInstance: 'Add instance',
  connectionTitle: 'Connection',
  connectionDescription:
    'URL and key are global: other deployments selecting this instance read the same copy.',
  baseUrl: 'Provider URL',
  secretName: 'Key variable name',
  secretNamePlaceholder: 'Environment variable name; empty = no auth',
  secretStatus: 'API key',
  secretSource: { env: 'process env', file: 'endpoint .env', none: 'not set' },
  secretValue: 'Key value',
  secretValuePlaceholder: 'Written to the endpoint .env only; never shown',
  saveSecret: 'Save key',
  secretSaved: 'Key written to the endpoint .env.',
  secretNameFirst: 'Save the key variable name before writing a key value.',
  multimodal: 'Accepts image input',
  endpointPath: 'Request path',
  extraHeaders: 'Extra headers (JSON object)',
  extraBody: 'Extra body (JSON object)',
  jsonObjectRequired: (label: string) => `${label} must be a JSON object`,
  advancedProtocolTitle: 'Protocol & Request Overrides',
  advancedProtocolDescription: 'Advanced options for OpenAI Responses compatible endpoints (custom path and extra JSON fields).',
  modelFieldLabel: 'Model identifier',
  effortFieldLabel: 'Reasoning effort',
  temperatureFieldLabel: 'Sampling temperature',
  specTitle: 'Model',
  specDescription: 'Configure model identifier, reasoning effort, temperature and token limits for this instance.',
  modelName: 'Exact model name',
  fetchModels: 'Fetch models',
  modelsFetched: (count: number) => `Fetched ${count} models.`,
  modelListFailed: (message: string) => `Could not fetch the model list: ${message}`,
  selectModel: 'Pick a model',
  unsupportedTier: (current: string) => `Unsupported current tier: ${current}`,
  thinkingOn: 'on',
  thinkingOff: 'off',
  effortPlaceholder: 'Reasoning effort; empty = endpoint default, none = off',
  effortAria: 'Reasoning effort',
  temperaturePlaceholder: 'Default temperature',
  modelAria: 'Model',
  tierAria: 'Reasoning tier',
  temperatureAria: 'Temperature',
  maxTokens: 'Max output tokens',
  contextWindow: 'Context window',
  serviceTier: 'Service tier',
  serverDefault: 'Server default',
  activate: 'Set as active provider instance',
  probe: 'Test endpoint',
  probeTitle: 'Test result',
  probeStatus: 'Status',
  probeOk: 'ok',
  probeFailed: 'failed',
  probeLatency: 'Latency',
  probeModel: 'Model echoed',
  probeUsage: 'Usage',
  probeUsageLine: (input: string, cached: string, output: string, reasoning: string) =>
    `input ${input} · cached ${cached} · output ${output} · reasoning ${reasoning}`,
  probeEncrypted: 'Encrypted reasoning',
  yes: 'yes',
  no: 'no',
  probeCost: 'Cost of this call',
  duplicate: 'Duplicate',
  duplicateName: 'Copy name',
  duplicateConfirm: 'Duplicate as',
  duplicated: 'Duplicated.',
  delete: 'Delete',
  deleteConfirmTitle: (name: string) => `Delete instance ${name}?`,
  deleteConfirmBody:
    'Removes the endpoint config and its .env. Whether another deployment selects it cannot be known here.',
  deleted: 'Deleted.',
  pricingTitle: 'Pricing',
  pricingDescription:
    'Historical records keep the quote in effect at request time. Custom quotes override module defaults per model and cost basis.',
  pricingUnset: 'No pricing set: calls on this endpoint count tokens but no amount on the usage page.',
  meters: {
    input: 'Input',
    cachedInput: 'Cache hit',
    uncachedInput: 'Uncached input',
    output: 'Output',
    reasoning: 'Reasoning',
    total: 'Total',
  },
  quoteUnknown: (model: string) => `${model}: quote unknown`,
  marginal: 'Marginal cost',
  equivalent: 'API-equivalent cost',
  perMillion: (label: string, rate: number) => `${label} ${rate}/M`,
  free: 'Explicitly free',
  bandsNote: 'Includes input bands or service tiers; billed by actual usage and service tier per request.',
  rateCached: 'Cache hit / M tokens',
  rateUncached: 'Uncached input / M tokens',
  rateOutput: 'Output / M tokens',
  currencyField: 'Currency',
  costFormNote:
    'Base rates apply to all models; input bands and service tiers go in the full rules below.',
  costFormOverridden:
    'The saved pricing is not a shape the three-rate form can express; the full rules below apply. Editing the form replaces them.',
  editFull: 'Advanced Pricing Rules (JSON)',
  fullNote:
    'An empty array restores the module default quote; an empty rules array means explicitly free. Full rules support input bands, service tiers and extra meters.',
  viewSnapshot: 'View active pricing snapshot',
};
export const panel = { zh, en };
