import { pick, type Language } from '../../core/language.ts';

/** Server side: ConfigGroup titles, validation errors, runtime and server state details. */
const zh = {
  tierOff: '关闭',
  tierOn: '开启',
  releaseRequired: '版本 tag 不能为空',
  backendUnsupported: (backend: string) => `本机平台没有后端 ${backend} 的官方构建`,
  runtimeDirString: '自备运行时目录必须是字符串',
  positiveInteger: (field: string) => `${field} 必须为正整数`,
  nonNegativeInteger: (field: string) => `${field} 必须为非负整数`,
  extraArgsString: '附加启动参数必须是字符串',
  autoStartBoolean: '自动启动必须是布尔值',
  notManaged: '这条端点没有开启托管',
  runtimeNotInstalled: '运行时还没装好',
  runtimeUnsupported: '本机平台没有这个后端的官方构建,填自备运行时目录',
  runtimePanel: '运行时',
  runtimePanelDescription: 'llama.cpp 官方二进制的下载、安装与 llama-server 进程的启停。',
  modelsPanel: '模型',
  modelsPanelDescription: 'llama-server 认得的模型:缓存里的、本机目录里的,以及正在下载的。',
  unknownPanel: '未知面板',
  unknownMethod: '未知操作',
  instanceNameRequired: '需要端点名',
  modelIdRequired: '需要模型 id',
  bodyRequired: '需要请求体',
  serverUnreachable: "llama-server 不可达；请检查端点地址与服务状态。",
  externalServer: '端点已有服务在跑(外部启动),不接管',
  starting: 'llama-server 启动中',
  spawnFailed: (message: string) => `进程启动失败: ${message}`,
  spawnBlocked: (exe: string) =>
    `Windows 启动 ${exe} 失败（UNKNOWN）。` +
    '启动失败时可在 Windows 安全中心核对拦截记录；若确认被拦截，请使用符合信任要求的运行时。',
  exited: (code: number | null, tail: string) => `进程退出 code=${code};stderr 尾部: ${tail}`,
  badBaseUrl: (baseUrl: string) => `baseUrl 无法解析出 host/port: ${baseUrl}`,
  missingBinary: (exe: string) => `运行时目录里没有 ${exe}`,
  healthTimeout: "/health 检查超时；请检查端点地址与服务状态。",
  downloadFailed: (file: string, message: string) => `下载 ${file} 失败: ${message}`,
  extractFailed: (file: string, message: string) => `解压 ${file} 失败: ${message}`,
  installBusy: '正在安装另一份运行时',
};
const en: typeof zh = {
  tierOff: 'Off',
  tierOn: 'On',
  releaseRequired: 'The release tag cannot be empty',
  backendUnsupported: (backend: string) => `No official build of backend ${backend} for this platform`,
  runtimeDirString: 'The own runtime directory must be a string',
  positiveInteger: (field: string) => `${field} must be a positive integer`,
  nonNegativeInteger: (field: string) => `${field} must be a non-negative integer`,
  extraArgsString: 'Extra launch arguments must be a string',
  autoStartBoolean: 'Auto start must be a boolean',
  notManaged: 'This endpoint is not managed',
  runtimeNotInstalled: 'The runtime is not installed yet',
  runtimeUnsupported: 'No official build for this backend on this platform; set an own runtime directory',
  runtimePanel: 'Runtime',
  runtimePanelDescription: 'Download and install the official llama.cpp binaries; start and stop the llama-server process.',
  modelsPanel: 'Models',
  modelsPanelDescription: 'Models llama-server knows: cached, in the local directory, and downloading.',
  unknownPanel: 'Unknown panel',
  unknownMethod: 'Unknown action',
  instanceNameRequired: 'An endpoint name is required',
  modelIdRequired: 'A model id is required',
  bodyRequired: 'A request body is required',
  serverUnreachable: "llama-server is unreachable; check the endpoint URL and server status.",
  externalServer: 'A server is already running at the endpoint (started externally); not taking over',
  starting: 'llama-server starting',
  spawnFailed: (message: string) => `Process failed to start: ${message}`,
  spawnBlocked: (exe: string) =>
    `Windows failed to start ${exe} (UNKNOWN). ` +
    'If startup fails, check Windows Security for a block record. If a block is confirmed, use a runtime that meets the trust requirements.',
  exited: (code: number | null, tail: string) => `Process exited code=${code}; stderr tail: ${tail}`,
  badBaseUrl: (baseUrl: string) => `Cannot derive host/port from baseUrl: ${baseUrl}`,
  missingBinary: (exe: string) => `No ${exe} in the runtime directory`,
  healthTimeout: "The /health check timed out; check the endpoint URL and server status.",
  downloadFailed: (file: string, message: string) => `Download of ${file} failed: ${message}`,
  extractFailed: (file: string, message: string) => `Extraction of ${file} failed: ${message}`,
  installBusy: 'Another runtime is being installed',
};
export type Text = typeof zh;
export const text = (language: Language) => pick(language, { zh, en });

/** Browser side: the two panels pick by `ctx.language`. */
const panelZh = {
  runtimeTitle: '运行时',
  modelsTitle: '模型',
  managedOff: "此端点由外部管理；开启托管后由 Cortico 管理 llama-server 进程。",
  enable: '开启托管',
  disable: '关闭托管',
  release: '版本',
  backend: '后端',
  runtimeDir: '运行时目录',
  ownRuntime: '自备',
  installStatus: '安装',
  installed: '已安装',
  absent: '未安装',
  downloading: '下载中',
  extracting: '解压中',
  install: '下载并安装',
  reinstall: '重新安装',
  sacWarning:
    "检测到 Windows 智能应用控制处于强制模式。" +
    '启动失败时可在 Windows 安全中心核对拦截记录；若确认被拦截，请使用符合信任要求的运行时。',
  server: '服务进程',
  serverSection: '服务进程与端点',
  serverSectionDesc: 'llama-server 本地服务管理与监听状态。',
  runtimeSection: '二进制运行环境',
  runtimeSectionDesc: '官方 llama.cpp 二进制包与运行依赖管理。',
  releaseHint: '上游 release tag，如 b10930；换了要重新下载。',
  backendHint: '按本机平台给出的官方构建;CUDA 版自动搭配上游的 cudart 包。',
  runtimeDirHint: '填了就不下载:目录里要有 llama-server 及其动态库(自编译、Linux CUDA、签过名的构建)。',
  browse: '选择目录',
  launchSection: '启动参数',
  launchSectionDesc: '在下一次启动 llama-server 时生效。',
  contextSize: '上下文长度(-c)',
  nGpuLayers: 'GPU 层数(-ngl)',
  parallel: '并发槽位(--parallel)',
  extraArgs: '附加启动参数',
  extraArgsHint: '按空格拆开追加到 llama-server 命令行。',
  autoStart: 'bot 启动时一并起 server',
  copyEndpoint: '复制端点',
  installRequired: '请先下载并安装运行时二进制，方可启动服务',
  status: '状态',
  endpoint: '端点',
  reachable: '可达',
  unreachable: '不可达',
  pid: '进程 PID',
  pendingNote: '启动参数已修改;停止并重新启动后生效。',
  start: '启动',
  stop: '停止',
  refresh: '刷新',
  phase: { stopped: '未运行', starting: '启动中', running: '运行中', error: '出错' } as Record<string, string>,
  modelId: '模型 ID',
  modelStatus: '状态',
  modality: '输入',
  path: '文件',
  actions: '操作',
  load: '加载',
  unload: '卸载',
  cancel: '取消',
  reload: '重扫',
  pull: '拉取',
  pullPlaceholder: 'HuggingFace 仓库,如 ggml-org/Qwen2.5-Coder-7B-Instruct-GGUF',
  localDir: '本机 GGUF 目录',
  cacheDir: '缓存目录',
  noModels: '暂无可用的 GGUF 模型：可通过上方输入拉取，或将 .gguf 文件放入本机目录后点击重扫。',
  modelStatusLabel: {
    loaded: '已加载',
    loading: '加载中',
    unloaded: '未加载',
    downloading: '下载中',
    sleeping: '休眠',
    failed: '加载失败',
    unknown: '在线',
  } as Record<string, string>,
  serverDown: "llama-server 不可达；请检查端点地址与服务状态。",
};
const panelEn: typeof panelZh = {
  runtimeTitle: 'Runtime',
  modelsTitle: 'Models',
  managedOff: "This endpoint is externally managed. Enable hosting to manage its llama-server process through Cortico.",
  enable: 'Enable hosting',
  disable: 'Disable hosting',
  release: 'Release',
  backend: 'Backend',
  runtimeDir: 'Runtime directory',
  ownRuntime: 'own',
  installStatus: 'Install',
  installed: 'installed',
  absent: 'not installed',
  downloading: 'downloading',
  extracting: 'extracting',
  install: 'Download and install',
  reinstall: 'Reinstall',
  sacWarning:
    "Windows Smart App Control is in enforced mode. " +
    'If startup fails, check Windows Security for a block record. If a block is confirmed, use a runtime that meets the trust requirements.',
  server: 'Server',
  serverSection: 'Server Process & Endpoint',
  serverSectionDesc: 'llama-server local process and listening status.',
  runtimeSection: 'Binary Runtime Environment',
  runtimeSectionDesc: 'Official llama.cpp binary and dependencies.',
  releaseHint: 'Upstream release tag, such as b10930; changing it downloads another build.',
  backendHint: 'Official builds for this platform; CUDA builds are paired with the upstream cudart package.',
  runtimeDirHint: 'When set nothing is downloaded: the directory holds llama-server and its shared libraries (self-built, Linux CUDA, signed builds).',
  browse: 'Choose directory',
  launchSection: 'Launch parameters',
  launchSectionDesc: 'Applied on the next llama-server start.',
  contextSize: 'Context size (-c)',
  nGpuLayers: 'GPU layers (-ngl)',
  parallel: 'Parallel slots (--parallel)',
  extraArgs: 'Extra launch arguments',
  extraArgsHint: 'Split on whitespace and appended to the llama-server command line.',
  autoStart: 'Start the server with the bot',
  copyEndpoint: 'Copy endpoint',
  installRequired: 'Install the runtime binary before starting the server',
  status: 'Status',
  endpoint: 'Endpoint',
  reachable: 'reachable',
  unreachable: 'unreachable',
  pid: 'Process PID',
  pendingNote: 'Launch parameters changed; stop and start again to apply them.',
  start: 'Start',
  stop: 'Stop',
  refresh: 'Refresh',
  phase: { stopped: 'stopped', starting: 'starting', running: 'running', error: 'error' } as Record<string, string>,
  modelId: 'Model ID',
  modelStatus: 'Status',
  modality: 'Input',
  path: 'File',
  actions: 'Actions',
  load: 'Load',
  unload: 'Unload',
  cancel: 'Cancel',
  reload: 'Rescan',
  pull: 'Pull',
  pullPlaceholder: 'HuggingFace repo, e.g. ggml-org/Qwen2.5-Coder-7B-Instruct-GGUF',
  localDir: 'Local GGUF directory',
  cacheDir: 'Cache directory',
  noModels: 'No models yet: pull one above, or drop GGUF files into the local directory and rescan.',
  modelStatusLabel: {
    loaded: 'loaded',
    loading: 'loading',
    unloaded: 'unloaded',
    downloading: 'downloading',
    sleeping: 'sleeping',
    failed: 'load failed',
    unknown: 'online',
  } as Record<string, string>,
  serverDown: "llama-server is unreachable; check the endpoint URL and server status.",
};
export const panel = { zh: panelZh, en: panelEn };
