# -*- mode: python ; coding: utf-8 -*-

# 控制中心只读 data/memory_graph.json 快照展示记忆图谱，不直连 chromadb。
# memory.py 顶层 try/except import chromadb → 缺失时优雅降级（_CHROMA_OK=False），
# 故不收集 chromadb 子模块，并排除其全部传递依赖，exe 从 ~122MB 降到 ~30MB。
hiddenimports = ['PySide6.QtUiTools']

excludes = [
    # ---- chromadb 及其传递依赖（控制中心读快照文件，不需要 chromadb） ----
    'chromadb',
    'chromadb_rust_bindings',
    'pypika',
    'tenacity',
    'mmh3',
    'orjson',
    'posthog',
    'watchfiles',
    'kubernetes',
    'grpcio',
    'opentelemetry',
    'opentelemetry_api',
    'opentelemetry_sdk',
    'opentelemetry_exporter_otlp_proto_common',
    'opentelemetry_exporter_otlp_proto_grpc',
    'opentelemetry_proto',
    'opentelemetry_semantic_conventions',
    # ---- HTTP 服务器栈（chromadb/openai 依赖，控制中心不发 HTTP） ----
    'uvicorn',
    'starlette',
    'fastapi',
    'gunicorn',
    'h11',
    'httptools',
    'websockets',
    'python_multipart',
    # ---- numpy（仅 embedding 缓存懒加载用，try/except 降级） ----
    'numpy',
    'scipy',
    'pandas',
    # ---- openai（memory.py 函数内懒加载，控制中心不调 LLM） ----
    'openai',
    # ---- httpx 栈（embedding.py 函数内懒加载，控制中心不调嵌入 API） ----
    'httpx',
    'httpcore',
    'anyio',
    'sniffio',
    'certifi',
    # ---- jieba（memory.py 函数内懒加载分词，控制中心不分词） ----
    'jieba',
    # ---- pydantic（chromadb/openai 依赖，控制中心不直接用） ----
    'pydantic',
    'pydantic_core',
    'pydantic_settings',
    'annotated_types',
    # ---- PIL/Pillow（chromadb 传递依赖，控制中心不做图像处理） ----
    'PIL',
    # ---- requests 栈（chromadb/openai 传递依赖） ----
    'requests',
    'urllib3',
    'charset_normalizer',
    'idna',
    # ---- 其他 chromadb 传递依赖 ----
    'click',
    'tqdm',
    'PyYAML',
    'yaml',
    'tokenizers',
    'huggingface_hub',
    'safetensors',
    'regex',
    'filelock',
    'frozenlist',
    'aiohttp',
    'aiosignal',
    'aiohappyeyeballs',
    'multidict',
    'yarl',
    'propcache',
    # ---- torch / transformers（主程序 TTS 推理用，控制中心不需要） ----
    'torch',
    'torchaudio',
    'torchvision',
    'transformers',
    'einops',
    'onnxruntime',
    'nltk',
    'pysbd',
    'py3langid',
    'wordsegment',
    'inflect',
    'pypinyin',
    'pydub',
    'sounddevice',
    'soundfile',
    'av',
    'psutil',
    'colorama',
    'coloredlogs',
    'humanfriendly',
    'rich',
    'markdown_it',
    'mdurl',
    'Pygments',
    'shellingham',
    'typer',
    'click',
    'APScheduler',
    'pytz',
    'tzdata',
    'tzlocal',
    'python_dateutil',
    'dateutil',
    'six',
    'bcrypt',
    'cffi',
    'pycparser',
    'pycryptodomex',
    'defusedxml',
    'lxml',
    'bs4',
    'soupsieve',
    'jsonschema',
    'rpds',
    'referencing',
    'attrs',
    'joblib',
    'packaging',
    'platformdirs',
    'distro',
    'mpmath',
    'sympy',
    'networkx',
    'Jinja2',
    'MarkupSafe',
    'tomli',
    'tomlkit',
    'typing_extensions',
    'typing_inspection',
    'grpc',
    'protobuf',
    'flatbuffers',
    'bilibili_api_python',
    'blivedm',
    'qrcode',
    'websocket',
    'websocket_client',
    'watchdog',
    'oauthlib',
    'requests_oauthlib',
    'pyreadline3',
    'durationpy',
    'groovy',
    'more_itertools',
    'typeguard',
    'overrides',
    'semantic_version',
    'pure_protobuf',
    'pybase64',
    'pyloudnorm',
    'pedalboard',
    'SudachiPy',
    'sudachipy',
    'SudachiDict_core',
    'importlib_metadata',
    'importlib_resources',
    'zipp',
    'future',
    'py3langid',
]


a = Analysis(
    ['ui\\control_center.py'],
    pathex=[],
    binaries=[],
    datas=[('ui\\control_center.ui', 'ui'), ('ui\\favicon.ico', 'ui')],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ControlCenter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['ui\\favicon.ico'],
)
