import { pick } from '../../core/language.ts';

const zh = {
  // index.ts
  navLabel: '用量与成本',
  navGroup: 'Core',
  pageTitle: '用量与成本',
  bucketAuto: '自动',
  bucketMinute: '分',
  bucketHour: '时',
  bucketDay: '天',
  bucketWeek: '周',
  bucketMonth: '月',
  presetToday: '今天',
  preset3: '近 3 天',
  preset7: '近 7 天',
  preset30: '近 30 天',
  preset90: '近 90 天',
  presetCustom: '自定义',
  metricCost: '成本',
  liveRefresh: '自动刷新',
  liveRefreshTitle: (sec: number) => `每 ${sec} 秒重取一次；离开本页自动停`,
  refresh: '刷新',
  granularity: '粒度',
  autoCurrency: '自动币种',
  basisMarginal: '边际费用',
  basisEquivalent: '等价 API 成本',
  ledger: '账本',
  compTitle: '成本构成',
  mainTitle: '用量时间序列',
  mainDesc: "可组合类型、角色与模型进行拆分。",
  split: '拆分',
  dimType: '类型',
  dimRole: '角色',
  dimModel: '模型',
  sortByShare: '占比排序',
  sortByShareTitle: '按各部分占比从大到小堆叠',
  callTitle: 'API 调用次数',
  headCalls: '调用',
  headInput: '输入 tok',
  headOutput: '输出 tok',
  headCache: '缓存命中',
  headCost: '成本',
  headAvg: '均价',
  byRole: '按角色',
  byModel: '按模型',
  cardKnownCost: '已知费用小计',
  unknown: '未知',
  cardCalls: '调用次数',
  cardAvgCost: '成功均价 / 次',
  approxTok: (tok: string) => `≈ ${tok} tok`,
  cardInput: '输入 token',
  hitRate: (pct: string) => `命中率 ${pct}`,
  cardOutput: '输出 token',
  reasoningShare: (pct: string) => `思维链 ${pct}`,
  cardCacheRate: '缓存命中率',
  cardCoverage: '报价覆盖',
  unpriced: (n: number) => `${n} 次在当前账本未完整计价`,
  cardPeak: '峰值',
  cardFailed: '失败流',
  failedCalls: (n: string) => `${n} 次`,
  burned: (tok: string) => `消耗 ≈ ${tok} tok`,
  noCostData: '暂无成本数据',
  partCacheHit: '命中缓存输入',
  partCacheMiss: '未命中输入',
  partOutput: '输出',
  partOther: '其他费用',
  noData: '无数据',
  autoBucket: (label: string) => `自动 → 按${label}`,
  rangeHint: (from: string, to: string, buckets: number) => `${from} ~ ${to} · ${buckets} 桶`,
  billingHint: '按请求时的报价快照统计。' +
    '总量包含失败、抢占与诊断请求；币种和费用口径分别汇总。',
  unknownUsage: (n: number) => ` ${n} 次请求的用量或缓存分布不完整。`,
  ledgerError: (pending: number, error: string) => ` 账目存储异常，${pending} 条待写入：${error}`,
  loadFailed: (msg: string) => '用量加载失败: ' + msg,
  loading: '加载中…',

  // chart.ts
  total: '合计',
  totalPrefix: '合计 ',
  callsUnit: ' 次',
  weekShort: (s: string) => s + '周',
  weekFull: (bucket: string) => bucket + ' 起 · 周',
  monthFull: (bucket: string) => bucket + ' · 月',
  restOmitted: '… 其余从略',
  tipFoot: (calls: number, hitRate: string, reasoning: string) =>
    `调用 ${calls} · 命中率 ${hitRate} · 思维链 ${reasoning}`,
  noCalls: '这个范围内没有调用记录',

  // labels.ts
  typeCacheHit: '命中缓存',
  typeCacheMiss: '未命中输入',
  typeOutput: '输出',
  typeOther: '其他费用 / 未分布输入',
};

const en: typeof zh = {
  // index.ts
  navLabel: 'Usage & cost',
  navGroup: 'Core',
  pageTitle: 'Usage & cost',
  bucketAuto: 'Auto',
  bucketMinute: 'Minute',
  bucketHour: 'Hour',
  bucketDay: 'Day',
  bucketWeek: 'Week',
  bucketMonth: 'Month',
  presetToday: 'Today',
  preset3: 'Last 3 days',
  preset7: 'Last 7 days',
  preset30: 'Last 30 days',
  preset90: 'Last 90 days',
  presetCustom: 'Custom',
  metricCost: 'Cost',
  liveRefresh: 'Auto refresh',
  liveRefreshTitle: (sec: number) => `Refetches every ${sec} s; stops when you leave this page`,
  refresh: 'Refresh',
  granularity: 'Granularity',
  autoCurrency: 'Auto currency',
  basisMarginal: 'Marginal cost',
  basisEquivalent: 'Equivalent API cost',
  ledger: 'Ledger',
  compTitle: 'Cost breakdown',
  mainTitle: 'Usage time series',
  mainDesc: "Combine type, role and model dimensions.",
  split: 'Split',
  dimType: 'Type',
  dimRole: 'Role',
  dimModel: 'Model',
  sortByShare: 'Sort by share',
  sortByShareTitle: 'Stack parts from largest share to smallest',
  callTitle: 'API calls',
  headCalls: 'Calls',
  headInput: 'Input tok',
  headOutput: 'Output tok',
  headCache: 'Cache hit',
  headCost: 'Cost',
  headAvg: 'Avg price',
  byRole: 'By role',
  byModel: 'By model',
  cardKnownCost: 'Known cost subtotal',
  unknown: 'unknown',
  cardCalls: 'Calls',
  cardAvgCost: 'Avg per successful call',
  approxTok: (tok: string) => `≈ ${tok} tok`,
  cardInput: 'Input tokens',
  hitRate: (pct: string) => `hit rate ${pct}`,
  cardOutput: 'Output tokens',
  reasoningShare: (pct: string) => `reasoning ${pct}`,
  cardCacheRate: 'Cache hit rate',
  cardCoverage: 'Price coverage',
  unpriced: (n: number) => `${n} calls not fully priced in the current ledger`,
  cardPeak: 'Peak',
  cardFailed: 'Failed calls',
  failedCalls: (n: string) => `${n} calls`,
  burned: (tok: string) => `used ≈ ${tok} tok`,
  noCostData: 'No cost data yet',
  partCacheHit: 'Cached input',
  partCacheMiss: 'Uncached input',
  partOutput: 'Output',
  partOther: 'Other charges',
  noData: 'No data',
  autoBucket: (label: string) => `Auto → by ${label}`,
  rangeHint: (from: string, to: string, buckets: number) => `${from} ~ ${to} · ${buckets} buckets`,
  billingHint: 'Computed from the price snapshot at request time. ' +
    'Totals include failed, preempted and diagnostic requests; currencies and cost bases are summed separately.',
  unknownUsage: (n: number) => ` ${n} requests have an incomplete usage or cache breakdown.`,
  ledgerError: (pending: number, error: string) => ` Ledger storage error, ${pending} entries pending: ${error}`,
  loadFailed: (msg: string) => 'Failed to load usage: ' + msg,
  loading: 'Loading…',

  // chart.ts
  total: 'Total',
  totalPrefix: 'Total ',
  callsUnit: ' calls',
  weekShort: (s: string) => s + ' wk',
  weekFull: (bucket: string) => bucket + ' · week',
  monthFull: (bucket: string) => bucket + ' · month',
  restOmitted: '… rest omitted',
  tipFoot: (calls: number, hitRate: string, reasoning: string) =>
    `calls ${calls} · hit rate ${hitRate} · reasoning ${reasoning}`,
  noCalls: 'No calls recorded in this range',

  // labels.ts
  typeCacheHit: 'Cached',
  typeCacheMiss: 'Uncached input',
  typeOutput: 'Output',
  typeOther: 'Other charges / unclassified input',
};

export const S = pick({ zh, en });
