import { pick } from '../core/language.ts';

const zh = {
  modeLight: '☀ 浅色',
  modeDark: '◐ 黑夜',
  modeSystem: '◒ 跟随系统',
  appearanceLight: '浅色',
  appearanceDark: '黑夜',
  groupPaper: "背景层级",
  groupInk: '文字与边界',
  groupState: '交互与状态',
  groupTimeline: '终端时间线',
  groupChart: '图表系列',
  token: {
    paper: '页面背景',
    'paper-2': '侧栏背景',
    sheet: '主卡片背景',
    'sheet-2': '次级卡片背景',
    'sheet-3': '压低底色',
    ink: '主要文字',
    'ink-soft': '次级文字',
    'ink-dim': '弱化文字',
    line: '细边界',
    'line-2': '常规边界',
    'line-strong': '强调边界',
    accent: '主强调',
    'accent-2': '次强调',
    'on-accent': '强调色上文字',
    ok: '成功 / 在线',
    warn: '提醒 / 系统',
    danger: '危险 / 失败',
    'ink-blue': 'Agent 标记',
    violet: '思考标记',
    'agent-surface': 'Agent 卡片底色',
    'world-bg': '世界事件底色',
    'world-ink': '世界事件文字',
    'bubble-bg': '发送气泡底色',
    'bubble-ink': '发送气泡文字',
    'tool-result': '工具结果文字',
    'chart-hit': '缓存命中',
    'chart-miss': '未命中输入',
    'chart-output': '模型输出',
    'chart-1': '系列 1',
    'chart-2': '系列 2',
    'chart-3': '系列 3',
    'chart-4': '系列 4',
    'chart-5': '系列 5',
    'chart-6': '系列 6',
    'chart-7': '系列 7',
    'chart-8': '系列 8',
  },
  schemeMint: '脑皮质薄荷',
  schemeMintNote: 'Logo 的薄荷绿、同色系层次与中性灰背景',
  schemeNavigator: '未来领航员',
  schemeNavigatorNote: '可缇 Corti 人设图的海军蓝、天蓝、白与淡粉',
  schemeCrabDaisy: '螃蟹和雏菊',
  schemeCrabDaisyNote: '赤陶、灰玫瑰与 Claude 网页灰阶',
  customScheme: '自定义方案',
  customNote: '自定义配色',
  copyOf: (name: string) => `${name} 副本`,
};

const en: typeof zh = {
  modeLight: '☀ Light',
  modeDark: '◐ Dark',
  modeSystem: '◒ System',
  appearanceLight: 'Light',
  appearanceDark: 'Dark',
  groupPaper: "Background layers",
  groupInk: 'Text & borders',
  groupState: 'Interaction & state',
  groupTimeline: 'Terminal timeline',
  groupChart: 'Chart series',
  token: {
    paper: 'Page background',
    'paper-2': 'Sidebar background',
    sheet: 'Main card',
    'sheet-2': 'Secondary card',
    'sheet-3': 'Recessed ground',
    ink: 'Primary text',
    'ink-soft': 'Secondary text',
    'ink-dim': 'Muted text',
    line: 'Hairline border',
    'line-2': 'Regular border',
    'line-strong': 'Strong border',
    accent: 'Primary accent',
    'accent-2': 'Secondary accent',
    'on-accent': 'Text on accent',
    ok: 'Success / online',
    warn: 'Notice / system',
    danger: 'Danger / failure',
    'ink-blue': 'Agent marker',
    violet: 'Reasoning marker',
    'agent-surface': 'Agent card ground',
    'world-bg': 'World event ground',
    'world-ink': 'World event text',
    'bubble-bg': 'Sent bubble ground',
    'bubble-ink': 'Sent bubble text',
    'tool-result': 'Tool result text',
    'chart-hit': 'Cache hit',
    'chart-miss': 'Uncached input',
    'chart-output': 'Model output',
    'chart-1': 'Series 1',
    'chart-2': 'Series 2',
    'chart-3': 'Series 3',
    'chart-4': 'Series 4',
    'chart-5': 'Series 5',
    'chart-6': 'Series 6',
    'chart-7': 'Series 7',
    'chart-8': 'Series 8',
  },
  schemeMint: 'Cortex Mint',
  schemeMintNote: 'Logo mint and tonal greens over neutral grey',
  schemeNavigator: 'Future Navigator',
  schemeNavigatorNote: 'Navy, sky blue, white and blush from Corti\'s character sheet',
  schemeCrabDaisy: 'Crab & Daisy',
  schemeCrabDaisyNote: 'Terracotta and dusty rose over Claude web greys',
  customScheme: 'Custom scheme',
  customNote: 'Custom palette',
  copyOf: (name: string) => `${name} copy`,
};

export const S = pick({ zh, en });
