import { pick, type Language } from '../../core/language.ts';

/** Server side: ConfigGroups, manifest labels and receipts built by `ProviderSettings`. */
const zh = {
  connectionDescription: '请求绑定在开始时固定；修改后从下一次请求生效。',
  baseUrl: '供应地址',
  secret: '密钥环境变量',
  secretDescription: '填写变量名；密钥内容由部署环境提供。',
  multimodal: '启用图像输入',
  activeInstanceLamp: '当前供应实例',
  availableLamp: '可用端点',
  availableLampNone: '没有可用端点',
  availableLampReady: (name: string) => `${name} 可用`,
  instancesBadge: '实例',
  settingsPanel: '实例与模型',
  settingsPanelDescription: "保存端点模型、价目及当前部署使用的端点。",
  saved: '参数已保存；下一次请求生效。',
  unknownGroup: '未知 Provider 参数组',
  groupOutOfScope: 'Provider 参数组只能修改所属实例',
  kindChange: '不能改变已有实例的模块类型',
  unknownInstance: '未知供应实例',
  foreignInstance: '供应实例不属于此模块',
  unknownPanel: '未知 Provider 面板',
  bodyRequired: '需要实例配置对象',
  nameRequired: '需要实例名',
  nameFormat: '实例名只能包含字母、数字、下划线与连字符',
  nameTaken: '实例名已存在',
  specRequired: '需要模型档对象',
  unknownMethod: '未知 Provider 操作',
  optionsObject: '原生参数必须是对象',
  deleteActive: '当前供应实例不能删除;先启用别的实例',
  secretNameRequired: '先填写密钥环境变量名,再写入密钥值',
  secretValueInvalid: '密钥值不能为空或含空白',
  modelsUnsupported: '此模块不提供模型列表',
  probeNoResponses: "请求返回 404；请检查供应地址、端点路径及服务支持的 API。",
  probeAuth: '鉴权失败:检查密钥变量名与密钥值',
  probeUnreachable: "连接或响应流失败；请检查网络、供应地址与代理。",
};
const en: typeof zh = {
  connectionDescription: 'Requests bind at start; changes apply from the next request.',
  baseUrl: 'Provider URL',
  secret: 'Secret environment variable',
  secretDescription: 'Enter the variable name; the deployment environment supplies the secret.',
  multimodal: 'Enable image input',
  activeInstanceLamp: 'Active provider instance',
  availableLamp: 'Usable endpoint',
  availableLampNone: 'No usable endpoint',
  availableLampReady: (name: string) => `${name} is usable`,
  instancesBadge: 'Instances',
  settingsPanel: 'Instances and models',
  settingsPanelDescription: "Save the endpoint model, pricing and the active endpoint for this deployment.",
  saved: 'Parameters saved; they apply from the next request.',
  unknownGroup: 'Unknown provider parameter group',
  groupOutOfScope: 'A provider parameter group can only modify its own instance',
  kindChange: 'The module type of an existing instance cannot be changed',
  unknownInstance: 'Unknown provider instance',
  foreignInstance: 'The provider instance does not belong to this module',
  unknownPanel: 'Unknown provider panel',
  bodyRequired: 'An instance configuration object is required',
  nameRequired: 'An instance name is required',
  nameFormat: 'Instance names may only contain letters, digits, underscores and hyphens',
  nameTaken: 'Instance name already exists',
  specRequired: 'A model spec object is required',
  unknownMethod: 'Unknown provider action',
  optionsObject: 'Native options must be an object',
  deleteActive: 'The active provider instance cannot be deleted; activate another instance first',
  secretNameRequired: 'Set the secret environment variable name before writing a key value',
  secretValueInvalid: 'The key value cannot be empty or contain whitespace',
  modelsUnsupported: 'This module does not list models',
  probeNoResponses: "The request returned 404; check the provider URL, endpoint path and supported APIs.",
  probeAuth: 'Authentication failed: check the secret variable name and the key value',
  probeUnreachable: "The connection or response stream failed; check the network, provider URL and proxy.",
};
export const text = (language: Language) => pick(language, { zh, en });
