import { pick } from '../../core/language.ts';

const zh = {
  // index.ts
  navLabel: '运行诊断',
  navGroup: 'Core',
  pageTitle: '运行诊断',
  subRun: '运行',
  subSessions: '会话统计',
  subEvents: '事件流',
  subRunlog: '运行日志',
  subData: '数据',
  subConfig: '配置',
  dataTitle: 'Core 的数据',
  dataDesc: '事件库、session、运行日志、用量流水这些 Core 自己攒下的存储。',
  configTitle: 'Core 配置',
  configDesc: '修改自动保存到 config.json。标有重启要求的配置在重启后生效,其余立即生效。',
  configEmpty: 'Core 没有可调配置。',
  netOffline: '接口不可达',

  // events.ts
  eventsDesc: '事件记录，agent 可查询。',
  allSources: '全部来源',
  showArchive: '显示原始归档',
  showArchiveTitle: '包括仅归档、未直接投递到上下文的事件',
  loadEarlier: '← 加载更早',
  evHeadTime: '时间',
  evHeadSource: '来源',
  evHeadType: '类型',
  evHeadText: '正文',
  noEvents: '暂无事件',

  // run.ts
  runTitle: '运行态',
  noStatus: '暂无状态',
  statContext: '上下文',
  statMessages: 'session 消息',
  statCache: '缓存命中',
  statRounds: '本批轮数',
  statBatches: '累计批次',
  statEvents: '事件库',
  statOnline: '终端在线',
  statRun: '运行',
  unitMsgs: '条',
  unitEvents: '条',
  unitPeople: '人',
  runPaused: '暂停',
  runBlocked: '闹钟阻断',
  runRunning: '进行',

  // runlog.ts
  currentRun: '当前 run',
  allLevels: '全部级别',
  areaPlaceholder: '区域前缀,如 worlds.minecraft', // arch-allow: 日志区域筛选框的示例前缀,只是示意文字
  grepPlaceholder: '正则,匹配内容与 data',
  roundPlaceholder: '轮次',
  roundField: '轮次',
  refresh: '刷新',
  runlogDesc: '运行日志，agent 不可见。',
  logHeadTime: '时间',
  logHeadLevel: '级别',
  logHeadArea: '区域',
  logHeadMsg: '内容',
  noLog: '暂无日志',

  // sessions.ts
  sessionsTitle: '会话统计',
  sessionsDesc: '本次运行中各 session 的 token 用量与缓存命中。跨重启统计见「用量与成本」。',
  sesHeadStatus: '状态',
  sesHeadCalls: '调用',
  sesHeadInput: '输入 tok',
  sesHeadCache: '缓存命中',
  sesHeadOutput: '输出 tok',
  sesHeadMsgs: '消息',
  noSessions: '暂无 session',
  running: '进行中',
  ended: '已结束',
};

const en: typeof zh = {
  // index.ts
  navLabel: 'Diagnostics',
  navGroup: 'Core',
  pageTitle: 'Diagnostics',
  subRun: 'Run',
  subSessions: 'Sessions',
  subEvents: 'Events',
  subRunlog: 'Run log',
  subData: 'Data',
  subConfig: 'Config',
  dataTitle: 'Core data',
  dataDesc: 'Storage Core accumulates on its own: the event store, the session, run logs and the usage ledger.',
  configTitle: 'Core config',
  configDesc: 'Changes save to config.json automatically. Settings marked for restart apply after restarting; the rest apply immediately.',
  configEmpty: 'Core has no tunable settings.',
  netOffline: 'API unreachable',

  // events.ts
  eventsDesc: 'Event records, queryable by the agent.',
  allSources: 'All sources',
  showArchive: 'Show raw archive',
  showArchiveTitle: 'Include archived events that are not delivered directly to the context',
  loadEarlier: '← Load earlier',
  evHeadTime: 'Time',
  evHeadSource: 'Source',
  evHeadType: 'Type',
  evHeadText: 'Text',
  noEvents: 'No events yet',

  // run.ts
  runTitle: 'Loop status',
  noStatus: 'No status yet',
  statContext: 'Context',
  statMessages: 'session messages',
  statCache: 'Cache hit',
  statRounds: 'Rounds this batch',
  statBatches: 'Total batches',
  statEvents: 'Event store',
  statOnline: 'Terminal online',
  statRun: 'Run',
  unitMsgs: 'msgs',
  unitEvents: 'events',
  unitPeople: 'users',
  runPaused: 'paused',
  runBlocked: 'schedule blocked',
  runRunning: 'running',

  // runlog.ts
  currentRun: 'Current run',
  allLevels: 'All levels',
  areaPlaceholder: 'Area prefix, e.g. worlds.minecraft', // arch-allow: 日志区域筛选框的示例前缀,只是示意文字
  grepPlaceholder: 'Regex, matches message and data',
  roundPlaceholder: 'Round',
  roundField: 'Round',
  refresh: 'Refresh',
  runlogDesc: 'Run logs, invisible to the agent.',
  logHeadTime: 'Time',
  logHeadLevel: 'Level',
  logHeadArea: 'Area',
  logHeadMsg: 'Message',
  noLog: 'No log entries',

  // sessions.ts
  sessionsTitle: 'Session stats',
  sessionsDesc: 'Token usage and cache hits for each session in this run. For history across restarts, see "Usage & cost".',
  sesHeadStatus: 'Status',
  sesHeadCalls: 'Calls',
  sesHeadInput: 'Input tok',
  sesHeadCache: 'Cache hit',
  sesHeadOutput: 'Output tok',
  sesHeadMsgs: 'Messages',
  noSessions: 'No sessions yet',
  running: 'running',
  ended: 'ended',
};

export const S = pick({ zh, en });
