import { pick } from '../core/language.ts';

const zh = {
  groupPersonas: 'Persona & Memory',
  groupWorlds: 'World',
  moduleInstancesAria: 'World 实例',
  navAria: '控制台导航',
  runResume: '继续运行',
  runPause: '暂停运行',
  runUnavailable: '运行控制不可用',
  shutdownAria: '关机',
  settingsAria: '设置',
  settingsTitle: '设置',
  finishing: '正在关闭…',
  shutdownTitle: '关机',
  restartAria: '重启',
  restartTitleSupervised: '重启',
  restartTitleUnsupervised: '退出后需手动启动',
  shutdownBody: '进程将退出，控制台连接将断开。',
  confirmShutdownTitle: '⚠ 关机',
  confirmRestartTitle: '⚠ 重启',
  restartSupervisedNote: '进程将重启。',
  restartUnsupervisedNote: '进程将退出，需要手动重新启动。',
  confirmShutdownAgainTitle: '⚠⚠ 确认关机?',
  confirmShutdownAgainBody: '停止运行并退出进程？',
  confirmRestartAgainTitle: '⚠⚠ 确认重启?',
  confirmRestartAgainSupervised: '退出并重新启动进程？',
  confirmRestartAgainUnsupervised: '退出进程？退出后需手动启动。',
  finishingToast: '正在关闭…',
  stepIncomplete: '未完成',
  doneShutdown: '已关机',
  doneRestartSupervised: '已退出，等待重新启动',
  doneRestart: '已退出',
  resultLocalIncomplete: '本地关闭步骤未全部完成',
  resultExternalUnverified: '本地已关机,外部状态未确认',
  resultUnverified: '关闭步骤已执行，状态未确认',
  resultDefault: '关闭步骤已执行。',
  noReceipt: (msg: string) =>
    `未收到关闭结果（${msg}）；进程可能已退出。详情见当前运行的 data/runs/<run>/log.jsonl 中的 shutdown 记录。`,
  docTitle: (name: string) => `控制台 · ${name}`,
  renameTitle: '点击改名',
  renameSaved: '展示名已保存',
  renameFailed: (msg: string) => `展示名没保存成:${msg}`,
};

const en: typeof zh = {
  groupPersonas: 'Persona & Memory',
  groupWorlds: 'World',
  moduleInstancesAria: 'World instances',
  navAria: 'Console navigation',
  runResume: 'Resume',
  runPause: 'Pause',
  runUnavailable: 'Run control unavailable',
  shutdownAria: 'Shut down',
  settingsAria: 'Settings',
  settingsTitle: 'Settings',
  finishing: 'Shutting down…',
  shutdownTitle: 'Shut down',
  restartAria: 'Restart',
  restartTitleSupervised: 'Restart',
  restartTitleUnsupervised: 'Manual startup required after exit',
  shutdownBody: 'The process will exit and disconnect the console.',
  confirmShutdownTitle: '⚠ Shut down',
  confirmRestartTitle: '⚠ Restart',
  restartSupervisedNote: 'The process will restart.',
  restartUnsupervisedNote: 'The process will exit and must be restarted manually.',
  confirmShutdownAgainTitle: '⚠⚠ Confirm shutdown?',
  confirmShutdownAgainBody: 'Stop running and exit the process?',
  confirmRestartAgainTitle: '⚠⚠ Confirm restart?',
  confirmRestartAgainSupervised: 'Exit and restart the process?',
  confirmRestartAgainUnsupervised: 'Exit the process? You must start it manually afterwards.',
  finishingToast: 'Shutting down…',
  stepIncomplete: 'incomplete',
  doneShutdown: 'Shut down',
  doneRestartSupervised: 'Exited; waiting to restart',
  doneRestart: 'Exited',
  resultLocalIncomplete: 'Local shutdown steps incomplete',
  resultExternalUnverified: 'Shut down locally; external state unverified',
  resultUnverified: 'Shutdown steps executed; state unverified',
  resultDefault: 'Shutdown steps executed.',
  noReceipt: (msg: string) =>
    `No shutdown result received (${msg}); the process may have exited. See the shutdown records in data/runs/<run>/log.jsonl for the current run.`,
  docTitle: (name: string) => `Console · ${name}`,
  renameTitle: 'Click to rename',
  renameSaved: 'Display name saved',
  renameFailed: (msg: string) => `Display name not saved: ${msg}`,
};

export const S = pick({ zh, en });
