import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

type Schema = {
  $ref?: string; type?: string | string[]; enum?: unknown[]; const?: unknown;
  oneOf?: Schema[]; anyOf?: Schema[]; allOf?: Schema[];
  properties?: Record<string, Schema>; required?: string[]; items?: Schema;
  additionalProperties?: boolean | Schema;
};

function render(s: Schema): string {
  if (s.$ref) return `Schemas[${JSON.stringify(s.$ref.split('/').at(-1))}]`;
  if ('const' in s) return JSON.stringify(s.const);
  if (s.enum) return s.enum.map(v => JSON.stringify(v)).join(' | ');
  if (s.oneOf || s.anyOf) return `(${(s.oneOf ?? s.anyOf)!.map(render).join(' | ')})`;
  if (s.allOf) return `(${s.allOf.map(render).join(' & ')})`;
  if (Array.isArray(s.type)) return s.type.map(type => render({ ...s, type })).join(' | ');
  if (s.type === 'array') return `Array<${render(s.items ?? {})}>`;
  if (s.properties || s.type === 'object') {
    const fields = Object.entries(s.properties ?? {}).map(([key, value]) =>
      `${JSON.stringify(key)}${s.required?.includes(key) ? '' : '?'}: ${render(value)};`);
    if (s.additionalProperties) fields.push(`[key: string]: ${s.additionalProperties === true ? 'unknown' : render(s.additionalProperties)};`);
    return fields.length ? `{ ${fields.join(' ')} }` : 'Record<string, unknown>';
  }
  if (s.type === 'integer' || s.type === 'number') return 'number';
  if (s.type === 'string' || s.type === 'boolean' || s.type === 'null') return s.type;
  return 'unknown';
}

const root = resolve('src/protocol/open-responses');
const raw = readFileSync(resolve(root, 'openapi.json'));
const api = JSON.parse(raw.toString('utf8')) as { info: { version: string }; components: { schemas: Record<string, Schema> } };
const entries = Object.entries(api.components.schemas);
const generated = [
  '// Generated by scripts/generate-open-responses.ts. Source: Open Responses (Apache-2.0).',
  `export const OPEN_RESPONSES_VERSION = ${JSON.stringify(api.info.version)};`,
  `export const OPEN_RESPONSES_SCHEMA_SHA256 = ${JSON.stringify(createHash('sha256').update(raw).digest('hex'))};`,
  'export interface Schemas {',
  ...entries.map(([name, schema]) => `  ${JSON.stringify(name)}: ${render(schema)};`),
  '}',
  `export type StreamEvent = ${entries.filter(([name]) => name.endsWith('StreamingEvent')).map(([name]) => `Schemas[${JSON.stringify(name)}]`).join(' | ')};`,
  `export const STREAM_EVENT_TYPES: ReadonlySet<string> = new Set(${JSON.stringify(entries.filter(([name]) => name.endsWith('StreamingEvent')).flatMap(([, schema]) => schema.properties?.type?.enum ?? [schema.properties?.type?.const]))});`,
  '',
].join('\n');
if (process.argv.includes('--check')) {
  if (readFileSync(resolve(root, 'generated.ts'), 'utf8') !== generated) throw new Error('Open Responses types are out of date');
} else writeFileSync(resolve(root, 'generated.ts'), generated);
