import { pick } from '../../core/language.ts';

const zh = {
  navLabel: 'World 总览',
  introTitle: 'World',
  sheetTitle: '装配状态',
  reloadPrefixBtn: '↻ 重载系统前缀',
  prefixReloaded: '前缀已重载',
  prefixReloadFailed: (msg: string) => `前缀重载失败: ${msg}`,
  updated: '已更新',
  toggleFailed: (msg: string) => `切换失败: ${msg}`,
  reloadNowTitle: '现在重载 system 前缀?',
  reloadNowBody: (name: string, wantVisible: boolean) =>
    (wantVisible ? `「${name}」已对 agent 重新可见。` : `「${name}」已对 agent 隐藏。`)
    + '\n\n事件投递已按新状态生效。重载会更新环境提示词与工具声明，保留已有对话。'
    + '取消后将在下次上下文交接或重开时更新。',
  deactivateTitle: (name: string) => `停用「${name}」?`,
  deactivateBody: (id: string) =>
    'World 会立即停止(它托管的外部进程与连接一并收尾),并写回 config.json 的 '
    + `worlds.${id}.enabled=false。agent 的环境提示词与工具随即撤下;再次激活按当前配置重建。`,
  activated: '已激活',
  deactivated: '已停用',
  activateFailed: (msg: string) => `激活失败: ${msg}`,
  deactivateFailed: (msg: string) => `停用失败: ${msg}`,
  restartTitle: (name: string) => `重启「${name}」?`,
  restartBody: "停止并重建 World，应用标有「重启 World 生效」的配置。托管进程与连接会停止后重新启动。",
  restarted: '已重启',
  restartFailed: (msg: string) => `重启失败: ${msg}`,
  lampAssembly: '装配',
  notInstalled: "不可用",
  notActive: '未激活',
  declaredByPersona: 'Persona定义',
  optionalAddon: '选配外挂',
  open: '打开',
  details: '→ 详情',
  toolsCount: (id: string, n: number) => `${id} · ${n} 个工具`,
  missingReasonDefault: "无法加载这个 World。",
  activateWorld: '激活 World',
  inactiveNoteActivatable: "激活后写入 config.json 并立即启动。",
  inactiveNoteManual: (id: string) => `本地有实现但没装配。要启用,把 config.json 里 worlds.${id}.enabled 改为 true 后重启。`,
  hideFromAgent: '对 agent 隐藏',
  showToAgent: '对 agent 显示',
  restartWorld: '重启 World',
  deactivateWorld: '停用 World',
  visibleToAgent: '对 agent 可见',
  hidden: '已隐藏',
  prefixPending: '前缀待重载',
  kvTools: '工具',
  kvNone: '（无）',
  kvWorkspace: '工作区',
  listSep: '、',
  driftNote: '事件投递已按新状态生效；环境提示词与工具声明将在前缀重载后更新。',
  sumVisible: (n: number) => `可见 ${n}`,
  sumHidden: (n: number) => `已隐藏 ${n}`,
  sumInactive: (n: number) => `未激活 ${n}`,
  sumMissing: (n: number) => `不可用 ${n}`,
  noWorlds: '没有任何 World',
  listLoadFailed: (msg: string) => `World 清单加载失败: ${msg}`,
  loading: '加载中…',
};

const en: typeof zh = {
  navLabel: 'World Overview',
  introTitle: 'Worlds',
  sheetTitle: 'Assembly status',
  reloadPrefixBtn: '↻ Reload system prefix',
  prefixReloaded: 'Prefix reloaded',
  prefixReloadFailed: (msg: string) => `Prefix reload failed: ${msg}`,
  updated: 'Updated',
  toggleFailed: (msg: string) => `Toggle failed: ${msg}`,
  reloadNowTitle: 'Reload the system prefix now?',
  reloadNowBody: (name: string, wantVisible: boolean) =>
    (wantVisible ? `"${name}" is visible to the agent again.` : `"${name}" is now hidden from the agent.`)
    + '\n\nEvent delivery already follows the new state. Reloading updates the environment prompt and tool declarations and keeps existing conversation messages. '
    + 'If cancelled, they update at the next context handoff or restart.',
  deactivateTitle: (name: string) => `Deactivate "${name}"?`,
  deactivateBody: (id: string) =>
    'The World stops immediately (its managed external processes and connections are wound down), and '
    + `worlds.${id}.enabled=false is written back to config.json. The agent's environment prompt and tools are withdrawn right away; activating again rebuilds it from the current config.`,
  activated: 'Activated',
  deactivated: 'Deactivated',
  activateFailed: (msg: string) => `Activation failed: ${msg}`,
  deactivateFailed: (msg: string) => `Deactivation failed: ${msg}`,
  restartTitle: (name: string) => `Restart "${name}"?`,
  restartBody: "Stops and rebuilds the World to apply settings marked for World restart. Managed processes and connections stop and restart.",
  restarted: 'Restarted',
  restartFailed: (msg: string) => `Restart failed: ${msg}`,
  lampAssembly: 'assembly',
  notInstalled: "Unavailable",
  notActive: 'Inactive',
  declaredByPersona: 'Declared by Persona',
  optionalAddon: 'Optional add-on',
  open: 'Open',
  details: '→ Details',
  toolsCount: (id: string, n: number) => `${id} · ${n} tools`,
  missingReasonDefault: "Could not load this World.",
  activateWorld: 'Activate World',
  inactiveNoteActivatable: "Activation saves to config.json and starts the World immediately.",
  inactiveNoteManual: (id: string) => `Implemented locally but not assembled. To enable it, set worlds.${id}.enabled to true in config.json and restart.`,
  hideFromAgent: 'Hide from agent',
  showToAgent: 'Show to agent',
  restartWorld: 'Restart World',
  deactivateWorld: 'Deactivate World',
  visibleToAgent: 'Visible to agent',
  hidden: 'Hidden',
  prefixPending: 'Prefix reload pending',
  kvTools: 'Tools',
  kvNone: '(none)',
  kvWorkspace: 'Workspace',
  listSep: ', ',
  driftNote: 'Event delivery already follows the new state; the environment prompt and tool declarations update after a prefix reload.',
  sumVisible: (n: number) => `Visible ${n}`,
  sumHidden: (n: number) => `Hidden ${n}`,
  sumInactive: (n: number) => `Inactive ${n}`,
  sumMissing: (n: number) => `Unavailable ${n}`,
  noWorlds: 'No worlds',
  listLoadFailed: (msg: string) => `Failed to load World list: ${msg}`,
  loading: 'Loading…',
};

export const S = pick({ zh, en });
