import { pick } from '../../core/language.ts';
import type { EnvPromptOrigin } from '../../../../core/prefix.ts';

const zh = {
  // index.ts
  title: '系统提示词',
  introDesc: "Ctrl+S 保存模板，重载后更新当前 session 前缀。来自代码的段只读。",
  reloadSession: '重载当前 session',
  reloading: '正在重载…',
  prefixReloaded: '前缀已重载',
  leaveUnsaved: "未保存的修改将丢失。离开？",
  saving: '保存中…',
  saved: '已保存',
  saveFailedFor: (title: string, msg: string) => `${title} 保存失败：${msg}`,
  savedList: (names: string) => `✓ 已保存 ${names}；重载后生效`,
  dirtyCount: (n: number) => `${n} 处改动还没保存（Ctrl+S）`,
  fillNowMultiline: '此刻填入（多行块）',
  fillNow: '此刻填入',
  varUnreported: "未提供此变量；占位符将原样保留。",
  varEmpty: '(此刻为空，会落到缺省文案)',
  flagEditable: (key: string, origin: EnvPromptOrigin | undefined) =>
    `可编辑：${key}${origin === 'deployment' ? '（本部署的覆盖）' : origin === 'package' ? '（bot 包覆盖；保存写入部署覆盖）' : origin === 'module' ? '（World 默认；保存后成为本部署的覆盖）' : ''}`,
  flagReadonly: '来自代码，只读',
  sourceMissing: (key: string) => `源「${key}」找不到`,
  fromCode: '来自代码',
  originDeployment: '本部署的覆盖',
  originPackage: "bot 包覆盖",
  originWorld: 'World 默认',
  listSep: '、',
  warnSep: '；',
  prefixEmpty: '前缀现在是空的',
  prefixUnavailable: "前缀预览不可用。",
  prefixStats: (n: number, tok: string) => `${n} 块 · 渲染后约 ${tok} tokens`,
  loadFailed: (msg: string) => `加载失败：${msg}`,

  // view.ts
  warnUnknownVars: (list: string) => `模板里的 ${list} 未提供值，占位符将原样保留`,
  warnUnusedVars: (list: string) => `${list} 声明了但没用到`,
  varPanelTitle: '这份模板的占位符',
  multiline: '多行',
  varUnreportedShort: "未提供此变量",
  varEmptyShort: '(此刻为空,会落到缺省文案)',
  leaveUnsavedNamed: (names: string) => `有未保存的模板改动（${names}）。离开并放弃？`,
  editableTemplate: '可编辑模板',
  cardDescDefault: '保存到源文件；重载系统前缀后对当前 session 生效。',
  loadedFromDeployment: "已载入本部署覆盖文件。",
  loadedFromPackage: "已载入 bot 包覆盖；保存写入本部署覆盖文件。",
  loadedFromWorld: "已载入 World 默认模板；保存写入本部署覆盖文件。",
  loadedFromSource: '已从源文件载入',
  unsaved: '● 未保存',
  saveToFile: '保存到文件',
  resetToWorld: '移除部署覆盖',
  savedResult: (result: string) => `✓ ${result}；重载前缀后生效`,
  saveFailed: (msg: string) => `保存失败：${msg}`,
  saveFailedToast: '保存失败',
  resetTitle: (title: string) => `删除「${title}」的部署覆盖？`,
  resetBody: '删除后使用 bot 包的覆盖版本；没有包覆盖时使用 World 默认版本。未保存的修改将丢失。',
  resetting: '恢复中…',
  resetDone: '已移除部署覆盖',
  resetFailed: (msg: string) => `恢复失败：${msg}`,
  resetFailedToast: '恢复失败',
  noTemplatesScoped: '这个归属下没有可编辑的模板',
  noTemplates: '没有可编辑的提示词模板',
  templatesLoadFailed: (msg: string) => `模板加载失败：${msg}`,

  // editor.ts
  saveHintDirty: '按 Ctrl+S 保存',
};

const en: typeof zh = {
  // index.ts
  title: 'System prompt',
  introDesc: "Ctrl+S saves templates; reload to update the current session prefix. Sections from code are read-only.",
  reloadSession: 'Reload current session',
  reloading: 'Reloading…',
  prefixReloaded: 'Prefix reloaded',
  leaveUnsaved: "Unsaved changes will be lost. Leave?",
  saving: 'Saving…',
  saved: 'Saved',
  saveFailedFor: (title: string, msg: string) => `${title} failed to save: ${msg}`,
  savedList: (names: string) => `✓ Saved ${names}; takes effect after reload`,
  dirtyCount: (n: number) => `${n} unsaved changes (Ctrl+S)`,
  fillNowMultiline: 'Filled in now (multi-line block)',
  fillNow: 'Filled in now',
  varUnreported: "Variable not provided; its placeholder remains unchanged.",
  varEmpty: '(empty right now; falls back to the default text)',
  flagEditable: (key: string, origin: EnvPromptOrigin | undefined) =>
    `Editable: ${key}${origin === 'deployment' ? ' (this deployment\'s override)' : origin === 'package' ? ' (the package\'s override; saving makes it this deployment\'s override)' : origin === 'module' ? ' (World default; saving makes it this deployment\'s override)' : ''}`,
  flagReadonly: 'From code, read-only',
  sourceMissing: (key: string) => `Source "${key}" not found`,
  fromCode: 'From code',
  originDeployment: 'This deployment\'s override',
  originPackage: "Bot package override",
  originWorld: 'World default',
  listSep: ', ',
  warnSep: '; ',
  prefixEmpty: 'The prefix is empty right now',
  prefixUnavailable: "Prefix preview unavailable.",
  prefixStats: (n: number, tok: string) => `${n} blocks · about ${tok} tokens rendered`,
  loadFailed: (msg: string) => `Load failed: ${msg}`,

  // view.ts
  warnUnknownVars: (list: string) => `${list} has no provided value; placeholders remain unchanged`,
  warnUnusedVars: (list: string) => `${list} declared but unused`,
  varPanelTitle: 'Placeholders in this template',
  multiline: 'multi-line',
  varUnreportedShort: "Variable not provided",
  varEmptyShort: '(empty right now; falls back to the default text)',
  leaveUnsavedNamed: (names: string) => `There are unsaved template changes (${names}). Leave and discard them?`,
  editableTemplate: 'editable template',
  cardDescDefault: 'Saved to the source file; takes effect for the current session after a system prefix reload.',
  loadedFromDeployment: "Loaded the deployment override.",
  loadedFromPackage: "Loaded the bot package override; saving writes the deployment override.",
  loadedFromWorld: "Loaded the World default; saving writes the deployment override.",
  loadedFromSource: 'Loaded from the source file',
  unsaved: '● Unsaved',
  saveToFile: 'Save to file',
  resetToWorld: 'Remove deployment override',
  savedResult: (result: string) => `✓ ${result}; takes effect after a prefix reload`,
  saveFailed: (msg: string) => `Save failed: ${msg}`,
  saveFailedToast: 'Save failed',
  resetTitle: (title: string) => `Delete the deployment override for "${title}"?`,
  resetBody: 'Uses the bot package\'s override after deletion, or the World default if the package has no override. Unsaved changes will be lost.',
  resetting: 'Restoring…',
  resetDone: 'Deployment override removed',
  resetFailed: (msg: string) => `Restore failed: ${msg}`,
  resetFailedToast: 'Restore failed',
  noTemplatesScoped: 'No editable templates under this owner',
  noTemplates: 'No editable prompt templates',
  templatesLoadFailed: (msg: string) => `Failed to load templates: ${msg}`,

  // editor.ts
  saveHintDirty: 'Ctrl+S to save',
};

export const S = pick({ zh, en });
