/**
 * SEND_GIFT_V2 夹具保留真实 protobuf 帧的逐字段布局；昵称、uid、头像 URL、粉丝牌名、交易号和 combo_id 均替换为假值。
 */
/** 粉丝团灯牌 ×1 = 100 金瓜子 = ¥0.10 */
export const PB_SMALL = [
  'CJFOEg/mtYvor5Xop4LkvJfnlLIaSmh0dHBzOi8vaTAuaGRzbGIuY29tL2Jmcy9mYWNlLzAwMDAwMDAwMDAwMDAwMDAwMDAw',
  'MDAwMDAwMDAwMDAwMDAwMDAwMDAuanBnQiwIopwBKB4yDOa1i+ivleeJjOWtkDjVkLQBQNWQtAFI/7f2BFD/0Z8DWAFgA1KD',
  'BQi88wESD+eyieS4neWboueBr+eJjBgBIAEoZDBkOGRCBGdvbGRKEzQ4MDAwMDAwMDAwMDAwMDAwMDFQgLOK1QZYAWI1YmF0',
  'Y2g6Z2lmdDpjb21ib19pZDoxMDAwMTozMDAwMzozMTE2NDoxNzAwMDAwMDAwLjAwMDBoCnBkeAWFAQAAgD+IAQGSAQbmipXl',
  'loLAAeLMAuoBEgoM5rWL6K+V5Li75pKtELPqAYoCygEIs+oBEsMBCgzmtYvor5XkuLvmkq0SSmh0dHBzOi8vaTAuaGRzbGIu',
  'Y29tL2Jmcy9mYWNlLzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAuanBnMloKDOa1i+ivleS4u+aS',
  'rRJKaHR0cHM6Ly9pMC5oZHNsYi5jb20vYmZzL2ZhY2UvMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw',
  'MC5qcGc6CyD///////////8BkgIHCIzg1wIQAZoC5QEKSmh0dHBzOi8vczEuaGRzbGIuY29tL2Jmcy9saXZlL2UwNTFkZmQ0',
  'NTU3Njc4ZjhlZGNhYzQ5OTNlZDAwYTA5MzVjYmQ5Y2MucG5nEktodHRwczovL2kwLmhkc2xiLmNvbS9iZnMvbGl2ZS8zMmI3',
  'OTkxMjBlMTYxNGZhNjI3NWI2ZDE1ZGE3YTUyYjIxZGQwMTlkLndlYnAqSmh0dHBzOi8vaTAuaGRzbGIuY29tL2Jmcy9saXZl',
  'LzgxNmY4YjdhYTIxMzI4ODhmY2U5MjhjZGZiMTdiOWNmMjFjYzA4MjMuZ2lmqgIUCAESBwj1t/ACEAISBwiM4NcCEAFYAWoC',
  'CBd6sQIIkU4SyQEKD+a1i+ivleinguS8l+eUshJKaHR0cHM6Ly9pMC5oZHNsYi5jb20vYmZzL2ZhY2UvMDAwMDAwMDAwMDAw',
  'MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMC5qcGcyXQoP5rWL6K+V6KeC5LyX55SyEkpodHRwczovL2kwLmhkc2xiLmNv',
  'bS9iZnMvZmFjZS8wMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwLmpwZzoLIP///////////wEaYAoJ',
  '57KJ5Lid5ZuiEBUYy6hpIJK7ygIoy6hpMMuoaUgBULPqAWDlE3oJIzNGQjRGNjk5ggEJIzNGQjRGNjk5igEJIzNGQjRGNjk5',
  'kgEHI0ZGRkZGRpoBCSMzRkI0RjZFNg==',
].join('');

/**
 * 亲密之旅 ×1 = 50000 金瓜子 = ¥50。
 */
export const PB_BIG = [
  'CJJOEg/mtYvor5Xop4LkvJfkuZkaSmh0dHBzOi8vaTAuaGRzbGIuY29tL2Jmcy9mYWNlLzAwMDAwMDAwMDAwMDAwMDAwMDAw',
  'MDAwMDAwMDAwMDAwMDAwMDAwMDAuanBnIgcjMDBEMUYxKANCLQj3hf/oAygTMg/mtYvor5XniYzlrZDkuZk4pLqeBkDAgYMG',
  'SMCBgwZQwIGDBlL1BAi4lwISDOS6suWvhuS5i+aXhRgBIAIo0IYDMNCGAzjQhgNCBGdvbGRKEzQ4MDAwMDAwMDAwMDAwMDAw',
  'MDFQ+seK1QZYAWI1YmF0Y2g6Z2lmdDpjb21ib19pZDoxMDAwMTozMDAwMzozMTE2NDoxNzAwMDAwMDAwLjAwMDBoCnDQhgN4',
  'CIUBAACAP4gBAZIBBuaKleWWgqgBAsAB4dAC6gESCgzmtYvor5XkuLvmkq0Qs+oBigLKAQiz6gESwwEKDOa1i+ivleS4u+aS',
  'rRJKaHR0cHM6Ly9pMC5oZHNsYi5jb20vYmZzL2ZhY2UvMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw',
  'MC5qcGcyWgoM5rWL6K+V5Li75pKtEkpodHRwczovL2kwLmhkc2xiLmNvbS9iZnMvZmFjZS8wMDAwMDAwMDAwMDAwMDAwMDAw',
  'MDAwMDAwMDAwMDAwMDAwMDAwMDAwLmpwZzoLIP///////////wGSAgCaAuoBCkpodHRwczovL3MxLmhkc2xiLmNvbS9iZnMv',
  'bGl2ZS9lMzkwNTdhNjJjMDVjMzgyNzJjYTMxYzFiMmNlMGVkNTc3NzA0N2NmLnBuZxJLaHR0cHM6Ly9pMC5oZHNsYi5jb20v',
  'YmZzL2xpdmUvMWE1ODU4N2FkZTA1OGQ4NDBlZDU4M2I2YjAwZTRiYTdjZTU3NmYwYy53ZWJwGOEuIAEqSmh0dHBzOi8vaTAu',
  'aGRzbGIuY29tL2Jmcy9saXZlL2M4YmJjNmRhY2UyMGNlODBjZGY5MGY5MjJhNzQ5NjE1NTE0ODhmZjAuZ2lmqgIAWAFqAggN',
  'ev8CCJJOEskBCg/mtYvor5Xop4LkvJfkuZkSSmh0dHBzOi8vaTAuaGRzbGIuY29tL2Jmcy9mYWNlLzAwMDAwMDAwMDAwMDAw',
  'MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAuanBnMl0KD+a1i+ivleinguS8l+S5mRJKaHR0cHM6Ly9pMC5oZHNsYi5jb20v',
  'YmZzL2ZhY2UvMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMC5qcGc6CyD///////////8BGq0BCgnn',
  'sonkuJ3lm6IQGBjLqGkgkrvKAij/0Z8DMMuoaUgBULPqAVgDYPUnakpodHRwczovL2kwLmhkc2xiLmNvbS9iZnMvbGl2ZS80',
  'ODM2MGM4ZjNiN2RlODAzMWU4NmZmMWVmNGEyZGZjMGVjMmE2MWMyLnBuZ3oJIzNGQjRGNjk5ggEJIzNGQjRGNjk5igEHIzVG',
  'QzdGNJIBByNGRkZGRkaaAQkjM0ZCNEY2RTY=',
].join('');
