"""initial schema

Revision ID: 20260703_0001
Revises:
Create Date: 2026-07-03 19:47:40.690785

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260703_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before any VECTOR column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recall_files",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("track", sa.String(), server_default="memory", nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.VECTOR(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_recall_files__scope", "recall_files", ["user_id", "agent_id"], unique=False)
    op.create_index(op.f("ix_recall_files_id"), "recall_files", ["id"], unique=False)
    op.create_index(op.f("ix_recall_files_name"), "recall_files", ["name"], unique=False)
    op.create_table(
        "resources",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("local_path", sa.String(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.VECTOR(), nullable=True),
        sa.Column("track", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_resources__scope", "resources", ["user_id", "agent_id"], unique=False)
    op.create_index(op.f("ix_resources_id"), "resources", ["id"], unique=False)
    op.create_table(
        "recall_file_segments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recall_file_id", sa.String(), nullable=False),
        sa.Column("track", sa.String(), server_default="memory", nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.VECTOR(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["recall_file_id"], ["recall_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_recall_file_segments__scope", "recall_file_segments", ["user_id", "agent_id"], unique=False)
    op.create_index(op.f("ix_recall_file_segments_id"), "recall_file_segments", ["id"], unique=False)
    op.create_index(
        op.f("ix_recall_file_segments_recall_file_id"), "recall_file_segments", ["recall_file_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recall_file_segments_recall_file_id"), table_name="recall_file_segments")
    op.drop_index(op.f("ix_recall_file_segments_id"), table_name="recall_file_segments")
    op.drop_index("ix_recall_file_segments__scope", table_name="recall_file_segments")
    op.drop_table("recall_file_segments")
    op.drop_index(op.f("ix_resources_id"), table_name="resources")
    op.drop_index("ix_resources__scope", table_name="resources")
    op.drop_table("resources")
    op.drop_index(op.f("ix_recall_files_name"), table_name="recall_files")
    op.drop_index(op.f("ix_recall_files_id"), table_name="recall_files")
    op.drop_index("ix_recall_files__scope", table_name="recall_files")
    op.drop_table("recall_files")
    # ### end Alembic commands ###
